name: Flujo de trabajo Auto Merge a Main
on:
    pull_request: 
        branches:
            - main
jobs:
    auto-merge:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Enable auto-merge
              run: |
                gh pr merge --auto --squash --repo ${{ github.repository }} ${{ github.event.pull_request.number }}
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}